version: '2.1'


# supply credentials through env vars on cluster master or .env
services:
    redis:
        image: 'redis:5.0.5'
    
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    mongo:
        image: mongo
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
        ports:
        - 27017:27017
        volumes:
            # mount on a NFS if deployed on a cluster
            - ./mongodata:/data/db

    webserver:
        image: puckel/docker-airflow:1.10.9
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - mongo
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MONGO_USER=airflow
            - MONGO_PASSWORD=airflow
            - MONGO_DB=analytics_db
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MONGO_USER=airflow
            - MONGO_PASSWORD=airflow
            - MONGO_DB=analytics_db
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./model-data:/usr/modeldir
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MONGO_USER=airflow
            - MONGO_PASSWORD=airflow
            - MONGO_DB=analytics_db
            - MODEL_DIR_HOST_PATH=E:\Studies\airflow-retrainer\model-data
            - DB_URI=mongodb://mongo:27017
        command: worker
